from django.contrib.auth.models import User
from adventure.models import Player, Room

Room.objects.all().delete()

r1 = Room(title="Room 1", description="""A candle barely illuminates the room, the ceiling is imperceptibly high, fading into darkness.""")
r2 = Room(title="Room 2", description="""A victrola play brassy jazz in the corner.""")
r3 = Room(title="Room 3", description="""Here, the floor is sticky. Every step threatens to separate you from your shoes.""")
r4 = Room(title="Room 4", description="""When you set down an open book to save your page for a moment, you are using the entire world as a bookmark.""")
r5 = Room(title="Room 5", description="""This room smells strongly of womens perfume. It reminds you of someone..""")
r6 = Room(title="Room 6", description="""As you enter, a gust of wind carries crunchy leaves across the floor. You shiver, there are no windows here.""")
r7 = Room(title="Room 7", description="""You're suddenly in a dewy meadow, the morning sun has just begun to rise, adding a welcome warmth to the crisp air.""")
r8 = Room(title="Room 8", description="""You can hear the ticking before you enter. There are clocks covering every available inch of the walls. No two are alike, none appear to be correct.""")
r9 = Room(title="Room 9", description="""Rainbow light dances through the stained glass ceiling.""")
r10 = Room(title="Room 10", description="""Deep green ivy crawls across the walls.""")
r11 = Room(title="Room 11", description="""A sharp smell, like copper pennies, hits your nose. Your heartbeat becomes a drumline in your ears as you realize it's the smell of blood.""")
r12 = Room(title="Room 12", description="""Rain pours down around you. The smell of wet rocks remind you of childhood.""")
r13 = Room(title="Room 13", description="""48 bottles of beer on the wall, 48 bottles of beer...""")
r14 = Room(title="Room 14", description="""In the distance, you can hear children laughing.""")
r15 = Room(title="Room 15", description="""You enter into darkness, you are overwhelmed with the scent of gasoline and you notice the floor is oily.""")
r16 = Room(title="Room 16", description="""The walls rattle around you, intensifying. A train horn blasts in your ears.""")
r17 = Room(title="Room 17", description="""Reaching out, the walls here are furry. The air smells earthy. Is it moss?""")
r18 = Room(title="Room 18", description="""Looking down, you're suddenly covered in bees.""")
r19 = Room(title="Room 19", description="""Crunch, crunch, crunch with every step... looking back you notice bugs crawling from wall to wall.""")
r20 = Room(title="Room 20", description="""Fiiiiiiive Goldennnnnn Riiiiiiiings.. Four calling birds, three french horns....""")
r21 = Room(title="Room 21", description="""It takes all of your might to fight against the wind, there is sand in your eyes, in your hair, in your teeth..""")
r22 = Room(title="Room 22", description="""With a splash, you are plunged into icy darkness. Coughing and shivering, you foot finally finds purchase on solid ground.""")
r23 = Room(title="Room 23", description="""Sweating, panting, you find yourself smothered in blistering heat.""")
r24 = Room(title="Room 24", description="""Your ankles are wet, puppy noses everywhere! You could stay here forever.""")
r25 = Room(title="Room 25", description="""All around you, lightning bugs flicker in the late dusk.""")
r26 = Room(title="Room 26", description="""The air is rich with decay, the wood floor is long softened with damp rot and spotted with mushrooms.""")
r27 = Room(title="Room 27", description="""In the damp air, dripping leaves hang heavily.""")
r28 = Room(title="Room 28", description="""Django.""")
r29 = Room(title="Room 29", description="""Jenga.""")
r30 = Room(title="Room 30", description="""A thin layer of clouds mask the half-moon, casting a blue glow across the ground.""")
r31 = Room(title="Room 31", description="""All the clutter around your house used to be money.""")
r32 = Room(title="Room 32", description="""Every light switch is also a dark switch.""")
r33 = Room(title="Room 33", description="""You can't be sad about having no emotions.""")
r34 = Room(title="Room 34", description="""We're all just made of mush and strings.""")
r35 = Room(title="Room 35", description="""Your hands wash themselves, you just stand there and supervise.""")
r36 = Room(title="Room 36", description="""https://i.redd.it/gd27lsjsuro31.jpg""")
r37 = Room(title="Room 37", description="""There's a snarl in the corner. Glancing over, Ralph Rodent, with yellow eyes, is looking right at you.""")
r38 = Room(title="Room 38", description="""You are ushered down a busy hallway as a swadled, screaming infant is shoved into your arms.""")
r39 = Room(title="Room 39", description="""In the center of the room, there is a caved stone pedestal holding a freshly baked pepperoni pizza.""")
r40 = Room(title="Room 40", description="""The air is briney, the sound of waves crashing calms you.""")
r41 = Room(title="Room 41", description="""Claw marks cover the floor and lower walls, something or someone was trying to escape.""")
r42 = Room(title="Room 42", description="""A heaping pile of rotting food lays before you. Flies fill the air and you hold your breath as you pass.""")
r43 = Room(title="Room 43", description="""A warm light emanates from a stone fireplace, flickering over two large chairs and between them sits a tray of cookies and cakes.""")
r44 = Room(title="Room 44", description="""You can see a stack of wooden crates in the corner, piled nearly to the ceiling. Tiny skeletons are all that remain of their contents.""")
r45 = Room(title="Room 45", description="""You get knocked down, but you get up again. Ain't ever gonna keep you down.""")
r46 = Room(title="Room 46", description="""A babbling waterfall trickles past, the forest around you is alive with birdsong.""")
r47 = Room(title="Room 47", description="""Above you, the sky is dense and bright with stars.""")
r48 = Room(title="Room 48", description="""A single mirror hangs on the wall. Looking into it, it does not reflect you, only the room around you.""")
r49 = Room(title="Room 49", description="""Countless steaming pipes run floor to ceiling, several are hissing or gurgling.""")
r50 = Room(title="Room 50", description="""Black bats cover the ceiling, you creep past trying not to disturb them.""")
r51 = Room(title="Room 51", description="""A toppled statue lies in the center of the room. It's cracked face is frozen in terror.""")
r52 = Room(title="Room 52", description="""Mournful weaping fills your ears. A dozen cloaked women kneel, rocking, facing the walls.""")
r53 = Room(title="Room 53", description="""A black fountain spits black water in an open courtyard""")
r54 = Room(title="Room 54", description="""A single pale, shriveled oyster lays before you. It's never seen starwars.""")
r55 = Room(title="Room 55", description="""Free range cattle dot the rolling green fields before you, gentle mooing fill the air.""")
r56 = Room(title="Room 56", description="""Orange and white koi splash in a pool before you.""")
r57 = Room(title="Room 57", description="""Like crunchy cornflakes, gold leaves rustle underfoot. Beauty in decay.""")
r58 = Room(title="Room 58", description="""You tentatively enter a candle-lit bedroom. Scented with lavendar and lilac, the room seems entirely draped in soft purple velvets and silks. You're suddenly acutely aware of your fatigue.""")
r59 = Room(title="Room 59", description="""A strange rhythmic clicking gets louder as you move forward. Rows of low windows line the walls and you see snowy mountains rush past. The room rocks gently like a cradle.""")
r60 = Room(title="Room 60", description="""Brown chicken, brown cow.""")
r61 = Room(title="Room 61", description="""A line of faces are carved into the walls, their hollow eyes seem to track you as you move.""")
r62 = Room(title="Room 62", description="""Tapestries decorate the walls of this room. Although they may once have been brilliant in hue, they now hang in graying tatters, the damage of time and neglect.""")
r63 = Room(title="Room 63", description="""Fire crackles and pops in a small cooking fire set in the center of the room. The smoke from a small burning creature on a spit curls up through a crack in the ceiling.""")
r64 = Room(title="Room 64", description="""This room is walled and floored with black marble veined with white.""")
r65 = Room(title="Room 65", description="""A strange ceiling is the focal point of the room before you. It's honeycombed with hundreds of holes as wide as your head.""")
r66 = Room(title="Room 66", description="""This tiny room holds a curious array of machinery. Heavy chains hang from the ceiling""")
r67 = Room(title="Room 67", description="""The smell of fresh bread beckons""")
r68 = Room(title="Room 68", description="""Dim light filters in from dusty windows.""")
r69 = Room(title="Room 69", description="""A small light flickers and fades in the distance. Then another. And another. As you approach, the light continues, flicker, fail. Flicker, fail. You never draw nearer, it never fades away.""")
r70 = Room(title="Room 70", description="""The smell of mold permeates the air.""")
r71 = Room(title="Room 71", description="""You realize with a tingle down your spine, you won't be leaving this place.""")
r72 = Room(title="Room 72", description="""Rats, everywhere.""")
r73 = Room(title="Room 73", description="""A door slams behind you!""")
r74 = Room(title="Room 74", description="""What's that smell? It's sour, like sweat.""")
r75 = Room(title="Room 75", description="""How did I get here?""")
r76 = Room(title="Room 76", description="""Stinking smoke wafts up from braziers made of iron, a row of hooded monks chant at the foot of a gilded alter.""")
r77 = Room(title="Room 77", description="""A floating orb produces a soft silvery blue light, the longer you look, the more you are drawn in by it.""")
r78 = Room(title="Room 78", description="""Dense fog lays heavily on the ground. """)
r79 = Room(title="Room 79", description="""You're in a bright, bustling coffee shop, toasty espresso fills your nostrils. Every stool is occupied and every eye is on you. You are naked.""")
r80 = Room(title="Room 80", description="""You find yourself prone, unable to stand. You have the energy and intent to move quickly away from this place, but you can only manage a sluggish crawl. Your muscles ache as you try to drag yourself forward.""")
r81 = Room(title="Room 81", description="""Sunlight pours in through tall windows, you see the shelves that reach to the ceiling are crammed with books and scrolls.""")
r82 = Room(title="Room 82", description="""You clutch the doorframe as you enter, instantly dizzy. Sinking to your knees you make your way forward, first feeling with your hands. The sky below you stretches out as white and orange clouds silently spill over eathother.""")
r83 = Room(title="Room 83", description="""In front of you, the floor seems dark and wriggling. With relief, you realize 30 black cats are sprawled out in thee sun, napping, purring, occasional tails twitching.""")
r84 = Room(title="Room 84", description="""White sheets cover dusty furniture all around. You only barely have room to maneuver through.""")
r85 = Room(title="Room 85", description="""You pass through quickly to avoid the snarling doberman chained to the floor.""")
r86 = Room(title="Room 86", description="""The cave before you is utterly made of crystals. From the doorway light, you can see a pale green cast through perfect geometric spires that criss-cross around you.""")
r87 = Room(title="Room 87", description="""The kitchen smells of garlic and onion, fresh produce is being washed and chopped, thick steaks are searing on a grate, a team of chef's work mechanically to prepare an immense feast.""")
r88 = Room(title="Room 88", description="""The bar is loud and crowded, the floor is sticky with spilled beer and the walls are yellowed with a century of cigarette smoke.""")
r89 = Room(title="Room 89", description="""You are running through a thick forest, pushing desperately past low branches and brush. Twigs snap behind you, and you are gripped by fear.""")
r90 = Room(title="Room 90", description="""Warm air touches your cheeks and fills your lungs as strong wind rustles the upper branches of tall oak trees.""")
r91 = Room(title="Room 91", description="""You’ve fixated on the idea that humanity is just a tiny speck in a vast universe. Everything is meaningless.""")
r92 = Room(title="Room 92", description="""Looking at your hands, you can't help but believe they are not your own. The wrinkled fingers and cracked knuckles betray your young heart.""")
r93 = Room(title="Room 93", description="""The room is swaying and swelling as if you were a ship on rough seas. A low long horn blast confirms your suspicion, and salty sea water licks the boards under your feet.""")
r94 = Room(title="Room 94", description="""As the door opens, it scrapes up frost from a floor covered in ice. You stumble your way into a black blizzard, your eyes stinging from relentless wind.""")
r95 = Room(title="Room 95", description="""Madness is being smart enough to know there's a better way to do something, but not smart enough to invent the way to do it.""")
r96 = Room(title="Room 96", description="""Being an adult is eating the crust, not because you like it, but because you paid for it.""")
r97 = Room(title="Room 97", description="""Everything you've ever bought, ever, still exists somewhere.""")
r98 = Room(title="Room 98", description="""Thick fog fills the space before you. You walk forward, arms outstretched, eyes desperately searching the grey air around you.""")
r99 = Room(title="Room 99", description="""A rickety rope bridge is all that separates you from a grisly fate in the crackling lava surging and hardening far below.""")
r100 = Room(title="Room 100", description="""You are staring down a silver unicorn, glowing blue like a full moon. It's eyes, unblinking, read the atoms of your soul and you weep on the ground at it's golden hooves.""")

#put all the rooms in a list and iterate (enumerate) through as each one is saved.
r1.save()
r2.save()
r3.save()
r4.save()
r5.save()
r6.save()
r7.save()
r8.save()
r9.save()
r10.save()
r11.save()
r12.save()
r13.save()
r14.save()
r15.save()
r16.save()
r17.save()
r18.save()
r19.save()
r20.save()
r21.save()
r22.save()
r23.save()
r24.save()
r25.save()
r26.save()
r27.save()
r28.save()
r29.save()
r30.save()
r31.save()
r32.save()
r33.save()
r34.save()
r35.save()
r36.save()
r37.save()
r38.save()
r39.save()
r40.save()
r41.save()
r42.save()
r43.save()
r44.save()
r45.save()
r46.save()
r47.save()
r48.save()
r49.save()
r50.save()
r51.save()
r52.save()
r53.save()
r54.save()
r55.save()
r56.save()
r57.save()
r58.save()
r59.save()
r60.save()
r61.save()
r62.save()
r63.save()
r64.save()
r65.save()
r66.save()
r67.save()
r68.save()
r69.save()
r70.save()
r71.save()
r72.save()
r73.save()
r74.save()
r75.save()
r76.save()
r77.save()
r78.save()
r79.save()
r80.save()
r81.save()
r82.save()
r83.save()
r84.save()
r85.save()
r86.save()
r87.save()
r88.save()
r89.save()
r90.save()
r91.save()
r92.save()
r93.save()
r94.save()
r95.save()
r96.save()
r97.save()
r98.save()
r99.save()
r100.save()

# Link rooms together
r100.connectRooms(r99, "w")
r100.connectRooms(r90, "n")
r99.connectRooms(r100, "e")
r98.connectRooms(r88, "n")
r98.connectRooms(r97, "w")
r97.connectRooms(r87, "n")
r97.connectRooms(r98, "e")
r96.connectRooms(r86, "n")
r96.connectRooms(r95, "w")
r95.connectRooms(r96, "e")
r95.connectRooms(r94, "w")
r94.connectRooms(r95, "e")
r94.connectRooms(r84, "n")
r93.connectRooms(r83, "n")
r93.connectRooms(r92, "w")
r92.connectRooms(r93, "e")
r92.connectRooms(r91, "w")
r91.connectRooms(r92, "e")
r91.connectRooms(r81, "n")
r90.connectRooms(r100, "s")
r90.connectRooms(r80, "n")
r89.connectRooms(r79, "n")
r88.connectRooms(r78, "n")
r88.connectRooms(r98, "s")
r87.connectRooms(r97, "s")
r87.connectRooms(r86, "w")
r86.connectRooms(r87, "e")
r86.connectRooms(r96, "s")
r85.connectRooms(r75, "n")
r84.connectRooms(r94, "s")
r84.connectRooms(r74, "n")
r83.connectRooms(r93, "s")
r82.connectRooms(r72, "n")
r82.connectRooms(r81, "w")
r81.connectRooms(r82, "e")
r81.connectRooms(r91, "s")
r80.connectRooms(r90, "s")
r80.connectRooms(r70, "n")
r79.connectRooms(r89, "s")
r79.connectRooms(r78, "w")
r78.connectRooms(r79, "e")
r78.connectRooms(r88, "s")
r77.connectRooms(r67, "n")
r77.connectRooms(r76, "w")
r76.connectRooms(r77, "e")
r76.connectRooms(r66, "n")
r75.connectRooms(r85, "s")
r75.connectRooms(r65, "n")
r75.connectRooms(r74, "w")
r74.connectRooms(r75, "e")
r74.connectRooms(r84, "s")
r74.connectRooms(r73, "w")
r73.connectRooms(r74, "e")
r73.connectRooms(r63, "n")
r72.connectRooms(r82, "s")
r72.connectRooms(r62, "n")
r71.connectRooms(r61, "n")
r70.connectRooms(r80, "s")
r70.connectRooms(r69, "w")
r69.connectRooms(r70, "e")
r69.connectRooms(r59, "n")
r68.connectRooms(r58, "n")
r68.connectRooms(r67, "w")
r67.connectRooms(r68, "e")
r67.connectRooms(r77, "s")
r1.connectRooms(r2, 'e')
r1.connectRooms(r11, 's')
r2.connectRooms(r1, 'w')
r2.connectRooms(r12, 's')
r3.connectRooms(r4, 'e')
r3.connectRooms(r13, 's')
r4.connectRooms(r3, 'w')
r4.connectRooms(r14, 's')
r4.connectRooms(r5, 'e')
r5.connectRooms(r4, 'w')
r5.connectRooms(r15, 's')
r6.connectRooms(r16, 's')
r6.connectRooms(r7, 'e')
r7.connectRooms(r6, 'w')
r7.connectRooms(r8, 'e')
r8.connectRooms(r7, 'w')
r8.connectRooms(r18, 's')
r8.connectRooms(r9, 'e')
r9.connectRooms(r8, 'w')
r9.connectRooms(r10, 'e')
r10.connectRooms(r9, 'w')
r10.connectRooms(r20, 's')
r11.connectRooms(r1, 'n')
r11.connectRooms(r21, 's')
r12.connectRooms(r2, 'n')
r12.connectRooms(r13, 'e')
r13.connectRooms(r12, 'w')
r13.connectRooms(r3, 'n')
r13.connectRooms(r23, 's')
r14.connectRooms(r4, 'n')
r14.connectRooms(r24, 's')
r15.connectRooms(r5, 'n')
r15.connectRooms(r25, 's')
r16.connectRooms(r6, 'n')
r16.connectRooms(r26, 's')
r17.connectRooms(r27, 's')
r18.connectRooms(r8, 'n')
r18.connectRooms(r28, 's')
r18.connectRooms(r19, 'e')
r19.connectRooms(r18, 'w')
r20.connectRooms(r10, 'n')
r21.connectRooms(r11, 'n')
r21.connectRooms(r31, 's')
r22.connectRooms(r32, 's')
r22.connectRooms(r23, 'e')
r23.connectRooms(r22, 'w')
r23.connectRooms(r13, 'n')
r24.connectRooms(r14, 'n')
r25.connectRooms(r15, 'n')
r25.connectRooms(r35, 's')
r25.connectRooms(r26, 'e')
r26.connectRooms(r25, 'w')
r26.connectRooms(r16, 'n')
r26.connectRooms(r27, 'e')
r27.connectRooms(r26, 'w')
r27.connectRooms(r17, 'n')
r28.connectRooms(r18, 'n')
r28.connectRooms(r29, 'e')
r29.connectRooms(r28, 'w')
r29.connectRooms(r30, 'e')
r29.connectRooms(r39, 's')
r30.connectRooms(r29, 'w')
r31.connectRooms(r21, 'n')
r31.connectRooms(r41, 's')
r32.connectRooms(r22, 'n')
r33.connectRooms(r43, 's')
r33.connectRooms(r34, 'e')
r34.connectRooms(r33, "w")
r34.connectRooms(r35, "e")
r35.connectRooms(r34, "w")
r35.connectRooms(r25, "n")
r35.connectRooms(r36, "e")
r36.connectRooms(r35, "w")
r36.connectRooms(r37, "e")
r37.connectRooms(r36, "w")
r37.connectRooms(r38, "e")
r37.connectRooms(r47, "s")
r38.connectRooms(r37, "w")
r38.connectRooms(r39, "e")
r39.connectRooms(r38, "w")
r39.connectRooms(r29, "n")
r39.connectRooms(r40, "e")
r40.connectRooms(r39, "w")
r40.connectRooms(r50, "s")
r41.connectRooms(r31, "n")
r41.connectRooms(r42, "e")
r42.connectRooms(r41, "w")
r42.connectRooms(r52, "s")
r43.connectRooms(r33, "n")
r43.connectRooms(r53, "s")
r44.connectRooms(r45, "e")
r44.connectRooms(r54, "s")
r45.connectRooms(r44, "w")
r45.connectRooms(r46, "e")
r46.connectRooms(r45, "w")
r47.connectRooms(r37, "n")
r47.connectRooms(r57, "s")
r48.connectRooms(r49, "e")
r48.connectRooms(r58, "s")
r49.connectRooms(r48, "w")
r49.connectRooms(r59, "s")
r50.connectRooms(r40, "n")
r51.connectRooms(r52, "e")
r51.connectRooms(r61, "s")
r52.connectRooms(r51, "w")
r52.connectRooms(r42, "n")
r52.connectRooms(r62, "s")
r53.connectRooms(r43, "n")
r53.connectRooms(r54, "e")
r54.connectRooms(r53, "w")
r54.connectRooms(r44, "n")
r54.connectRooms(r64, "s")
r55.connectRooms(r56, "e")
r55.connectRooms(r65, "s")
r56.connectRooms(r55, "w")
r56.connectRooms(r66, "s")
r57.connectRooms(r47, "n")
r57.connectRooms(r58, "e")
r58.connectRooms(r57, "w")
r58.connectRooms(r48, "n")
r58.connectRooms(r68, "s")
r59.connectRooms(r49, "n")
r59.connectRooms(r60, "e")
r59.connectRooms(r69, "s")
r60.connectRooms(r59, "w")
r61.connectRooms(r51, "n")
r61.connectRooms(r71, "s")
r62.connectRooms(r52, "n")
r62.connectRooms(r63, "e")
r62.connectRooms(r72, "s")
r63.connectRooms(r62, "w")
r63.connectRooms(r73, "s")
r64.connectRooms(r54, "n")
r65.connectRooms(r55, "n")
r65.connectRooms(r75, "s")
r66.connectRooms(r56, "n")
r66.connectRooms(r76, "s")

players=Player.objects.all()
for p in players:
  p.currentRoom=r1.id
  p.save()

